AWSTemplateFormatVersion: '2010-09-09'

Description: Cloud Student Hub website infrastructure

Parameters:

  Environment:
    Type: String

    AllowedValues:
      - Test
      - Production

    Description: Deployment environment

Resources:

  WebsiteBucket:
    Type: AWS::S3::Bucket

    Properties:

      WebsiteConfiguration:
        IndexDocument: index.html
        ErrorDocument: index.html

      Tags:

        - Key: Environment
          Value: !Ref Environment

        - Key: Project
          Value: CloudStudentHub


  WebsiteBucketPolicy:
    Type: AWS::S3::BucketPolicy

    Properties:

      Bucket: !Ref WebsiteBucket

      PolicyDocument:

        Version: '2012-10-17'

        Statement:

          - Sid: PublicRead

            Effect: Allow

            Principal: '*'

            Action:
              - s3:GetObject

            Resource:
              - !Sub '${WebsiteBucket.Arn}/*'


Outputs:

  BucketName:

    Description: Website S3 bucket name

    Value: !Ref WebsiteBucket


  WebsiteURL:

    Description: Website URL

    Value:
      Fn::GetAtt:
        - WebsiteBucket
        - WebsiteURL